"""Fix user model

Revision ID: 668a82073724
Revises: d9c5523a2988
Create Date: 2025-07-06 11:02:10.706588

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '668a82073724'
down_revision = 'd9c5523a2988'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ### 